// Prepares a deploy. No dependencies; Wrangler runs it via "build.command".
//  1. templates/*.html -> src/templates_bundle.py  (Python Workers only bundle .py modules)
//  2. static files     -> public/                   (the static-assets directory; keeps source files private)
// Both outputs are generated and git-ignored. The script is idempotent and only
// touches files whose content changed, because `wrangler dev` watches these
// paths and would otherwise rebuild in a loop (and on Windows, deleting a
// watched directory fails with EPERM).
import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));

function writeIfChanged(path, content) {
  if (existsSync(path) && Buffer.compare(readFileSync(path), content) === 0) return;
  writeFileSync(path, content);
}

const partials = {};
for (const f of readdirSync(join(root, "templates")).filter((f) => f.startsWith("_") && f.endsWith(".html"))) {
  partials[f] = readFileSync(join(root, "templates", f), "utf8");
}
// Flask resolves {% include "_x.html" %} itself; the Worker bundle gets them inlined.
const inline = (src) => src.replace(/\{%\s*include\s+"([^"]+)"\s*%\}/g, (_, name) => {
  if (!(name in partials)) throw new Error(`unknown include: ${name}`);
  return partials[name].replace(/\n$/, "");
});
const templates = {};
for (const f of readdirSync(join(root, "templates")).filter((f) => f.endsWith(".html") && !f.startsWith("_")).sort()) {
  templates[f] = inline(readFileSync(join(root, "templates", f), "utf8"));
}
if (!templates["index.html"]) throw new Error("templates/index.html is missing");
writeIfChanged(
  join(root, "src", "templates_bundle.py"),
  Buffer.from("# GENERATED by scripts/build.mjs - do not edit\nTEMPLATES = " + JSON.stringify(templates, null, 1) + "\n"),
);

const pub = join(root, "public");
mkdirSync(join(pub, "static"), { recursive: true });
const wanted = new Set([".gitkeep"]);
const rootFiles = [
  "robots.txt", "sitemap.xml", "llms.txt", "site.webmanifest", "favicon.ico",
  "favicon-16x16.png", "favicon-32x32.png", "apple-touch-icon.png",
  "android-chrome-192x192.png", "android-chrome-512x512.png",
];
const copies = rootFiles.map((f) => [f, f]);
for (const f of readdirSync(join(root, "static"))) copies.push([join("static", f), join("static", f)]);
for (const [from, to] of copies) {
  if (!existsSync(join(root, from))) throw new Error(`missing static file: ${from}`);
  wanted.add(to.split("\\").join("/"));
  writeIfChanged(join(pub, to), readFileSync(join(root, from)));
}

// Prune stale copies (best effort).
function prune(dir, rel = "") {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name), r = rel ? `${rel}/${name}` : name;
    if (statSync(p).isDirectory()) prune(p, r);
    else if (!wanted.has(r)) { try { rmSync(p); } catch { /* ignore */ } }
  }
}
prune(pub);
console.log(`build: ${Object.keys(templates).length} templates -> src/templates_bundle.py, ${copies.length} static files -> public/`);
