"""Cloudflare Python Worker entry point.

Serves the same routes as app.py (Flask). Flask/WSGI is synchronous and cannot
await the Workers `fetch`, so routing is done here and the outbound requests
use the Workers fetch API instead of `requests`.
"""
import asyncio
import json
import ipaddress
from urllib.parse import urlparse, parse_qs

from js import fetch, AbortSignal, Object
from pyodide.ffi import to_js
from workers import WorkerEntrypoint, Response

from render import HomeTemplate
from security import html_response_parts
from seo_core import normalize_domain, parse_page
from templates_bundle import TEMPLATES, SECURITY_HEADERS  # generated by scripts/build.mjs

# Free plan: 50 subrequests/request (every redirect hop counts) and ~10 ms CPU.
# Each domain costs >= 3 subrequests, so the default leaves headroom for
# redirects. Raise MAX_DOMAINS (wrangler.jsonc "vars") on a paid plan.
DEFAULT_MAX_DOMAINS = 5
MAX_BODY_CHARS = 400_000  # parse at most this much HTML to bound CPU time
MAX_FORM_CHARS = 20_000
PAGE_TIMEOUT_MS = 8000
PROBE_TIMEOUT_MS = 5000
USER_AGENT = "Mozilla/5.0 (compatible; SEOScoreBot/1.0; +https://www.freeseoaudit.site/)"

# Parsed/rendered at import time so it lands in the deploy-time memory snapshot.
HOME = HomeTemplate(TEMPLATES["index.html"])
HOME_EMPTY = HOME.render(results=[])

PAGES = {
    "/about": "about.html",
    "/contact": "contact.html",
    "/blog": "blog.html",
    "/blog/free-seo-audit-tool": "blog1.html",
    "/blog/seo-tips-for-beginners": "blog2.html",
    "/blog/improve-website-seo-score": "blog3.html",
    "/blog/on-page-seo-checklist": "blog4.html",
    "/privacy": "privacy.html",
    "/terms": "terms.html",
}



def html_response(body):
    """HTML page with the security headers and a per-response CSP nonce."""
    body, headers = html_response_parts(body, SECURITY_HEADERS)
    headers["content-type"] = "text/html; charset=utf-8"
    return Response(body, headers=headers)


def plain_response(body, status=200, headers=None):
    return Response(body, status=status, headers={**SECURITY_HEADERS, **(headers or {})})


ERROR_ROW = {"status": "Error", "title": "Error", "meta": "Error",
             "words": "-", "h1": "-", "h2": "-", "links": "-",
             "robots": "Error", "sitemap": "Error"}
SKIPPED_ROW = {"title": "-", "meta": "-", "words": "-", "h1": "-", "h2": "-",
               "links": "-", "robots": "-", "sitemap": "-"}


def is_public_host(domain):
    """Reject anything that is not a plain public hostname (IPs, localhost, userinfo...)."""
    host = domain.split("/", 1)[0].split("?", 1)[0].split("#", 1)[0].lower()
    if not host or any(c in host for c in " \t\\@%"):
        return False
    if host.startswith("["):  # IPv6 literal
        return False
    if ":" in host:
        host = host.rsplit(":", 1)[0]
    try:
        ipaddress.ip_address(host)
        return False
    except ValueError:
        pass
    return "." in host and not host.endswith((".local", ".localhost", ".internal", ".lan"))


async def _get(url, timeout_ms):
    init = to_js(
        {"signal": AbortSignal.timeout(timeout_ms), "redirect": "follow",
         "headers": {"user-agent": USER_AGENT}},
        dict_converter=Object.fromEntries,
    )
    return await fetch(url, init)


async def _exists(url):
    try:
        resp = await _get(url, PROBE_TIMEOUT_MS)
        status = resp.status
        try:  # only the status matters; release the connection without reading the body
            if resp.body:
                await resp.body.cancel()
        except Exception:
            pass
        return "Yes" if status == 200 else "No"
    except Exception:
        return "Error"


async def analyze(domain):
    data = {"domain": domain}
    clean = normalize_domain(domain)
    if not is_public_host(clean):
        data.update(ERROR_ROW)
        return data
    base = "https://" + clean

    async def page():
        try:
            resp = await _get(base, PAGE_TIMEOUT_MS)
            html = await resp.text()
            data.update(parse_page(html[:MAX_BODY_CHARS], base))
            data["status"] = resp.status
            data["final_url"] = resp.url
            data["redirected"] = bool(resp.redirected)
            data["size_bytes"] = len(html.encode("utf-8"))
        except Exception:
            data.update({k: ERROR_ROW[k] for k in ("status", "title", "meta", "words", "h1", "h2", "links")})

    async def robots():
        data["robots"] = await _exists(base + "/robots.txt")

    async def sitemap():
        data["sitemap"] = await _exists(base + "/sitemap.xml")

    await asyncio.gather(page(), robots(), sitemap())
    return data


async def analyze_all(domains, limit):
    # Max 6 simultaneous outbound connections per invocation: two domains at a
    # time (3 requests each) so no request waits in the queue and times out.
    gate = asyncio.Semaphore(2)

    async def one(d):
        async with gate:
            return await analyze(d)

    results = list(await asyncio.gather(*(one(d) for d in domains[:limit])))
    for d in domains[limit:]:
        results.append({"domain": d, "status": f"Skipped (max {limit} per audit)", **SKIPPED_ROW})
    return results


class Default(WorkerEntrypoint):
    def _max_domains(self):
        try:
            return max(1, int(getattr(self.env, "MAX_DOMAINS", DEFAULT_MAX_DOMAINS)))
        except (TypeError, ValueError):
            return DEFAULT_MAX_DOMAINS

    async def fetch(self, request):
        path = urlparse(request.url).path
        if len(path) > 1:
            path = path.rstrip("/")
        method = str(request.method)

        if path == "/":
            if method not in ("GET", "HEAD", "POST"):
                return plain_response("Method Not Allowed", 405, {"allow": "GET, HEAD, POST"})
            if method != "POST":
                return html_response(HOME_EMPTY)
            form = parse_qs((await request.text())[:MAX_FORM_CHARS])
            domains = [d.strip() for d in form.get("domains", [""])[0].splitlines() if d.strip()]
            results = await analyze_all(domains, self._max_domains())
            if "application/json" in (request.headers.get("accept") or ""):
                return plain_response(json.dumps(results), headers={"content-type": "application/json"})
            return html_response(HOME.render(results=results))

        if path in PAGES:
            return html_response(TEMPLATES[PAGES[path]])

        # robots.txt, sitemap.xml, llms.txt, favicons and /static/* are served by
        # the static assets binding before the Worker runs; anything else is a 404.
        return plain_response("Not Found", 404)
